name: Aggregate yesterday

on:
  schedule:
    - cron: '0 1 * * *'
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Run scrape-all API
        run: |
          curl -XPOST -H "Authorization: Bearer ${{ secrets.SERVICE_TOKEN }}" https://dashboard.downalytics.dev/api/admin/aggregate-snapshots
